Feature/#40 UsedPost CRUD
Neo-Market/BE-NeoMarket pull request #47
Opened 2024-08-14 02:57 UTC by gato-46

2024-08-14 03:38 UTC, jiione requested changes
코드 작성 수고하셨습니다!!!
수정 부탁드립니다 👍

2024-08-14 03:38 UTC, jiione commented on src/main/java/com/neo/neomarket/service/impl/UsedPostServiceImpl.java
> +        return CreateDTO;
이미 같은 값을 재 정의 하는 것은 비효율 적으로 보입니다. 또한, 반환 값은 `void`나 `id` 만 반환 부탁드립니다.

2024-08-14 03:38 UTC, jiione commented on src/main/java/com/neo/neomarket/controller/UsedPostController.java
> +    @PatchMapping("used/{id}")
모든 값을 파라미터로 받아 변경하므로 `@PutMapping` 으로 변경 부탁드립니다.

2024-08-14 03:38 UTC, jiione commented on src/main/java/com/neo/neomarket/service/impl/UsedPostServiceImpl.java
> +        return UpdatDTO;
반환 타입 `void`로 부탁드립니다.

2024-08-14 03:38 UTC, jiione commented on src/main/java/com/neo/neomarket/dto/usedpost/UsedPostCreateDTO.java
> +//    private List<String> pictures;
필요없는 주석은 삭제 부탁드립니다.

2024-08-14 03:38 UTC, jiione commented on src/main/java/com/neo/neomarket/dto/usedpost/UsedPostDTO.java
> +    private long price;
래퍼 클래스로 변경 부탁드립니다.

2024-08-14 03:38 UTC, jiione commented on src/main/java/com/neo/neomarket/service/impl/UsedPostServiceImpl.java
> +        UsedPostEntity upost = usedPostRepository.findById(id).orElseThrow(() -> new CustomException(ErrorCode.NOT_EXIST_POST));
변수 명 카멜 케이스를 사용하는 것이 좋아보입니다.

2024-08-14 03:38 UTC, jiione commented on src/main/java/com/neo/neomarket/service/impl/UsedPostServiceImpl.java
> +        }
예외 처리 `CustomException` 사용 부탁드립니다.

2024-08-14 06:04 UTC, jiione requested changes
고생 많으셨습니다!!

2024-08-14 06:04 UTC, jiione commented on src/main/java/com/neo/neomarket/service/impl/UsedPostServiceImpl.java
> +        uPost.setPrice(usedPostUpdateDTO.getPrice());
update 하는 값 수정 부탁드립니다.

2024-08-14 15:37 UTC, lotuxsoo commented
ip주소 올라간 커밋 수정 부탁 드립니다!!

2024-08-15 23:38 UTC, jiione approved these changes
LGTM 👍

2024-08-15 23:38 UTC, merged